language: go

sudo: false

go:
  - 1.9.1
  - "1.10"

before_install:
  - wget "http://ftp.debian.org/debian/pool/main/s/shellcheck/shellcheck_0.4.4-4_amd64.deb"
  - dpkg -x shellcheck_0.4.4-4_amd64.deb $HOME
  - export PATH=$HOME/usr/bin:$PATH
  - go get -u github.com/signalfx/gobuild
  - go get -u github.com/alecthomas/gometalinter
  - gometalinter --install
  - gem install mdl --version 0.4.0

script:
  - export PATH=$HOME/gopath/bin:$PATH
  - export GOCOVERDIR_DIR="."
  - ./scripts/travis_check.sh
