language: go

go:
  - 1.2
  - 1.3
  - release

install:
  - sudo apt-get update
  - sudo apt-get install -y ghc6 ghc6-prof ghc6-doc cabal-install
  - cabal update
  - cabal install cabal-install
  - cabal install shellcheck
  - sudo ln ~/.cabal/bin/shellcheck /usr/bin/shellcheck
  - go get github.com/golang/lint/golint
  - go get code.google.com/p/go.tools/cmd/vet
  - go get github.com/stretchr/testify/mock
  - go get code.google.com/p/go.tools/cmd/cover
  - gem install mdl
  - go get -u ./...

script:
  - export PATH=$HOME/gopath/bin:$PATH
  - ./travis_check.sh
