language: go

go:
  - 1.2
  - 1.3
  - release

install:
  - apt-get install -y shellcheck
  - go get github.com/golang/lint/golint
  - go get code.google.com/p/go.tools/cmd/vet
  - go get github.com/stretchr/testify/mock
  - go get code.google.com/p/go.tools/cmd/cover
  - gem install mdl
  - go get -u ./...

script:
  - export PATH=$HOME/gopath/bin:$PATH
  - ./travis_check.sh
