language: go

go:
  - 1.1
  - 1.2
  - 1.3
  - release
  - tip

install:
  - go get github.com/golang/lint/golint
  - go get code.google.com/p/go.tools/cmd/vet
  - go get github.com/stretchr/testify/mock
  - go get ./...

script:
  - ./travis_check.sh
  - go test -v ./...
