language: go

go:
  - 1.3
  - 1.4
  - tip

install:
  - sudo apt-get update
  - sudo apt-get install -y ghc6 ghc6-prof ghc6-doc cabal-install shellcheck
#  - cabal update || cabal update || cabal update # damn you travis-ci.org
#  - cabal install shellcheck
#  - sudo ln ~/.cabal/bin/shellcheck /usr/bin/shellcheck
  - go get github.com/stretchr/testify/mock
  - go get github.com/tools/godep
  - go get -u github.com/cep21/goverify
  - gem install mdl
  - go get -d -v ./... && go build -v ./...

script:
  - export PATH=$HOME/gopath/bin:$PATH
  - ./travis_check.sh
