[vars]
  ignoreDirs = [".git", "Godeps"]
  duplLimit = "300"
  testCoverage = 100.0

[metalinter]
  [metalinter.ignored]
    coverageignored = "ignored is unused"
  [metalinter.enabled]
    golint = true
    gofmt = true
    varcheck = true
    maligned = true
    gocyclo = true
    vet = true
    deadcode = true
    unconvert = true
    structcheck = true
    ineffassign = true
    errcheck = true
