[vars]
  duplLimit = "300"

[metalinter]
  [metalinter.ignored]
    coverageignored = "ignored is unused"
  [metalinter.enabled]
    golint = true
    gofmt = true
    varcheck = true
    aligncheck = false
    gocyclo = true
    vet = true
    deadcode = true
